### ISSUE TITLE
Unable to select content when the side panel is a child of the Map Component

### ISSUE THREAD

**Issue by erssebaggala** [eferhatg/react-leaflet-sidetabs#2]
I moved the SideBar component under the Map component because in full screen the side bar would disappear!.

**Comment by erssebaggala** [comment]
I was able to disable dragging and zoom with code below. I hope this will help someone else.

```
const map = this.refs.map.leafletElement;

var div = L.DomUtil.get('gis_sidebar');
L.DomEvent.on(div, 'mouseover', function(){
	map.dragging.disable();
	map.touchZoom.disable();
	map.doubleClickZoom.disable();
	map.scrollWheelZoom.disable();
});

L.DomEvent.on(div, 'mouseout', function(){
	map.dragging.enable();
	map.touchZoom.enable();
	map.doubleClickZoom.enable();
	map.scrollWheelZoom.enable();
});
```

**Comment by erssebaggala** [comment]
@eferhatg Perhaps this should be incorporated into the plugin

**Comment by eferhatg** [comment]
> I moved the SideBar component under the Map component because in full screen the side bar would disappear!.

I couldn't catch an issue like this. Is there any way to simulate?

**Comment by eferhatg** [comment]
> @eferhatg Perhaps this should be incorporated into the plugin

I'll try it. Thanks.  

By the way, pull requests are welcome.
